repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.12
  hooks:
    - id: ruff-check          # Run the linter.
    - id: ruff-format         # Run the formatter.

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: trailing-whitespace   # 줄 끝 공백 제거
    - id: end-of-file-fixer     # 파일 끝 개행 추가
    - id: check-yaml            # yaml 문법 검사
    - id: check-json            # json 문법 검사
    - id: pretty-format-json    # json 포멧터
      args: ["--autofix"]       # json 자동 포맷
      files: "\.json$"